# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
    build:
          docker:
              # Use the same Docker base as the project
              - image: python:3.7.3-stretch

          working_directory: ~/udacity-project5-ml-microservice-docker-kubernetes

          steps:
              - checkout

              # Download and cache dependencies
              - restore_cache:
                    keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

              - run:
                    name: Install nvm & npm
                    command: |
                        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
                        export NVM_DIR="$HOME/.nvm" 
                        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
                        nvm install node
                        npm install jsonlint -g
                    
              - run:
                    name: install dependencies
                    command: |
                        python3 -m venv venv
                        . venv/bin/activate
                        make install
                        # Install hadolint
                        wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-Linux-x86_64 &&\
                        chmod +x /bin/hadolint

              - save_cache:
                    paths:
                        - ./venv
                    key: v1-dependencies-{{ checksum "requirements.txt" }}

              # run lint!
              - run:
                    name: run lint
                    command: |
                        . venv/bin/activate
                        make lint 
